version: "3"

services:
  web:
    hostname: web
    image: nginx:alpine
    volumes:
      - ./web/html:/usr/share/nginx/html:rw
      - ./web/conf:/etc/nginx/conf.d:rw
    ports:
      - "80:80"
    environment:
      - _NGINX_WWW_BASE_URL=
      - _NGINX_BRAND_NAME=
    command:
      sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"